# FROM openjdk:8-jdk-alpine
# VOLUME /tmp
# ARG JAR_FILE=./target/spring-boot-docker-ssl-0.0.1.jar
# COPY ${JAR_FILE} spring-boot-ssl.jar
# ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/spring-boot-ssl.jar"]
FROM maven:latest AS MAVEN_BUILD
COPY pom.xml /build/
COPY src /build/src/
WORKDIR /build/
RUN mvn clean install -DskipTests
FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=MAVEN_BUILD /build/target/spring-boot-docker-ssl-0.0.1.jar /app/
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom", "-jar", "spring-boot-docker-ssl-0.0.1.jar"]