version: '3'
services:
  keycloak:
    build: ./keycloak
    container_name: keycloak
    environment:
      - KEYCLOAK_USER='admin'
      - KEYCLOAK_PASSWORD='admin'
    ports:
      - 8080:8080
    volumes:
            - "./keycloak:/tmp/"
    command: ["-Dkeycloak.migration.action=import \
	       -Dkeycloak.migration.provider=dir \
	       -Dkeycloak.profile.feature.upload_scripts=enabled \
	       -Dkeycloak.migration.dir=/tmp/bak \
	       -Dkeycloak.migration.strategy=IGNORE_EXISTING \
               -b 0.0.0.0"]
